### ISSUE TITLE
When using RandomizedSearchCV, fit() got an unexpected keyword argument 'epochs'...

### ISSUE THREAD

**Issue by jiacheng-ye** [ageron/tf2_course#5]
```
rnd_search_cv = RandomizedSearchCV(keras_reg, param_distribs, n_iter=10, cv=3, verbose=2)
rnd_search_cv.fit(X_train_scaled, y_train, epochs=100,
                           validation_data=(X_valid_scaled, y_valid),
                           callbacks=[keras.callbacks.EarlyStopping(patience=10)])
```
then it occurs:
```
TypeError: fit() got an unexpected keyword argument 'epochs'
```
and the fit() of RandomizedSearchCV is like this, 
```
class RandomizedSearchCV(BaseSearchCV)  
    def fit(self, X, y=None, groups=None)
```
and I'm confusing about how to pass epochs, validation_data and callbacks to this function...
Waiting for answering, thinks :)

**Comment by ageron** [comment]
Hi @Stark-JC ,
Thanks for your feedback.  Perhaps you have an older version of Scikit-Learn? You need at least 0.20, what version are you using?

**Comment by jiacheng-ye** [comment]
@ageron Thanks a lot. I find my scikit-learn version is 0.18.2. And it's fixed after I update to 0.20.
